services:
  - type: web
    name: projectmanager
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=8192 